name: Go CI/CD

on:
  push:
    branches: 
      - staging
      - ario
      - rizki
  pull_request:
    branches: 
      - staging
      - ario
      - rizki

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/api_pos/Point-Of-Sale/backend-golang
            git stash
            git checkout ario
            git pull origin ario
            go get .
            go build
            sudo systemctl daemon-reload
            sudo systemctl restart goposapi.service
