name: Go CI/CD

on:
  push:
    branches: 
      - staging
      - ario
      - rizki

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the branch name
        id: branch
        run: echo ::set-output name=branch::${{ github.ref }}
        
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/pos_service_api/Point-Of-Sale/backend-golang
            git stash
            git checkout ${{ steps.branch.outputs.branch }}
            git pull origin ${{ steps.branch.outputs.branch }}
            go get .
            go build
            sudo systemctl daemon-reload
            sudo systemctl restart goposapi.service
